mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
ipv6: false
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 8.8.8.8
    - 1.1.1.1
proxies:
  - name: HK-443
    type: vless
    server: 154.37.216.240
    port: 443
    uuid: 333996f3-d8d4-42b6-bede-c23c9f0c7545
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.cloudflare.com
    client-fingerprint: chrome
    reality-opts:
      public-key: -ujLsbMCP6HOH_7e2emxQvRCGgeYTmJU2mp5HkUHVn0
      short-id: a1b2c3d4
  - name: HK-80
    type: vless
    server: 154.37.216.240
    port: 80
    uuid: 333996f3-d8d4-42b6-bede-c23c9f0c7545
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.cloudflare.com
    client-fingerprint: chrome
    reality-opts:
      public-key: -ujLsbMCP6HOH_7e2emxQvRCGgeYTmJU2mp5HkUHVn0
      short-id: a1b2c3d4
  - name: HK-HY2
    type: hysteria2
    server: 154.37.216.240
    port: 8443
    password: HkHy2-8f3aK2
    sni: www.cloudflare.com
    skip-cert-verify: true
    udp: true
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - HK-HY2
      - HK-80
      - HK-443
      - DIRECT
rules:
  - MATCH,PROXY
